### ISSUE TITLE
使用中发现的问题。。

### ISSUE THREAD

**Issue by Kissycat** [zfdx123/openwrt#1]
我想应该是些bug吧，但是我折腾了一天，刷了N次也没有解决...
情况如下：

1.wan口删除后再添加会显示接口未连接（变灰），dhcp自然也获取不到上级路由的地址；

2.用r33作AP时，将交换机两个可用端口设置到一个vlan上，r33设置为静态ip，关闭自身dhcp。此时有线桥接的设备是正常的，可以获取到另一个口子上路由器分配的地址。但是我们的C312B自身就完全连接不到网络，也ping不通同网段的设备，WiFi上的设备自然也没有获取到网关路由分配的地址；

3.r33那个用不了的wan口，用swconfig命令可以检测到在switch0的5号端口上，修改network_02文件后，luci的交换机界面也是正常识别千兆已连接，但很奇怪，网络接口上如果使用switch0的vlan都是显示没有连接（图标灰色），还是用不了。

老哥有时间看看呗。

话说官方固件有没有可能通过opkg给它直接上一套op21呢，只上个luci感觉都不错了呀..

**Comment by Kissycat** [comment]
https://forum.openwrt.org/t/dsa-two-switch-setup-in-devicetree/107091/20
这里好像有将wan口合并到rtl8367交换机方法的样子

**Comment by zfdx123** [comment]
> 我想应该是些bug吧，但是我折腾了一天，刷了N次也没有解决... 情况如下：
> 
> 1.wan口删除后再添加会显示接口未连接（变灰），dhcp自然也获取不到上级路由的地址；
> 
> 2.用r33作AP时，将交换机两个可用端口设置到一个vlan上，r33设置为静态ip，关闭自身dhcp。此时有线桥接的设备是正常的，可以获取到另一个口子上路由器分配的地址。但是我们的C312B自身就完全连接不到网络，也ping不通同网段的设备，WiFi上的设备自然也没有获取到网关路由分配的地址；
> 
> 3.r33那个用不了的wan口，用swconfig命令可以检测到在switch0的5号端口上，修改network_02文件后，luci的交换机界面也是正常识别千兆已连接，但很奇怪，网络接口上如果使用switch0的vlan都是显示没有连接（图标灰色），还是用不了。
> 
> 老哥有时间看看呗。
> 
> 话说官方固件有没有可能通过opkg给它直接上一套op21呢，只上个luci感觉都不错了呀..

是的wan无法使用，这是一个已知问题，现在lan1是wan口，其他的问题应该是op配置文件与底层没有关系，wan口我会尝试解决，抱歉这么晚才看到这个is

**Comment by zfdx123** [comment]
> 

似乎并没有什么帮助，我们已经查询过大量资料，我们会后续慢慢解决，至于合并21我并不会这么做，不过我会合并到22

**Comment by Kissycat** [comment]
> > 
> 
> 似乎并没有什么帮助，我们已经查询过大量资料，我们会后续慢慢解决，至于合并21我并不会这么做，不过我会合并到22

希望以后可以解决吧😂
